Add extension to gtw
inextensodigital/terraform-aws-lambda-graphql pull request #30
Opened 2020-10-28 09:40 UTC by jlecomte-IED

2020-10-28 12:01 UTC, vibou requested changes

2020-10-28 12:01 UTC, vibou commented on variables.tf
> +  default     =  []
- `null` as default value should be better than an empty array
- in addition it should be related to the environment. So I would see a map such as

```
object(list(string))
```

with default value

```
{
  "dev": null,
  "preprod": null,
  "prod": null
}
```

2020-10-28 12:31 UTC, jlecomte-IED commented on variables.tf
> +variable "gateway_type" {
fixed

2020-10-29 11:14 UTC, vibou approved these changes

2020-10-29 11:18 UTC, merged